config/routes.rb
BestBookmark::Application.routes.draw do
  

  get "profiles/show"

  devise_for :users
  
  root to: 'bookmarks#index'
  resources :bookmarks
  resources :categories

  devise_scope :user do 
    get 'register', to: 'devise/registrations#new', as: :register
    get 'login', to: 'devise/sessions#new', as: :login
    get 'logout', to: 'devise/sessions#destroy', as: :logout
  end

  get 'feed', to: 'bookmarks#index', as: :feed
  get '/:id', to: 'profiles#show'

end

app/models/bookmark.rb
class Bookmark < ActiveRecord::Base
  attr_accessible :description, :url, :title

  #relationships
  belongs_to :user
  has_many :categories

  validates_format_of :url, :with => URI::regexp(%w(http https))

end

app/models/category.rb
class Category < ActiveRecord::Base
  attr_accessible :description, :title

  #relationships
  has_and_belongs_to_many :bookmarks
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me,
  				  :first_name, :last_name, :profile_name
  # attr_accessible :title, :body

  validates :first_name, presence: true

  validates :last_name, presence: true

  validates :profile_name, 
                presence: true,
                uniqueness: false,
                format: {
                    with: /^[a-zA-Z0-9_-]+$/,
                    message: 'Must be formatted correctaly'
                }

def full_name
    first_name + " " + last_name
  end

  def gravatar_url
    stripped_email = email.strip
    downcased_email = stripped_email.downcase
    hash = Digest::MD5.hexdigest(downcased_email)

    "http://gravatar.com/avatar/#{hash}"
  end

  #relationships
  has_many :bookmarks
  has_many :categories
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/bookmarks_controller.rb
class BookmarksController < ApplicationController

  before_filter :authenticate_user!

  # GET /bookmarks
  # GET /bookmarks.json
  # def index
  #   @user = User.find_by_profile_name(params[:id])
  #   @bookmarks = @user.bookmarks.all

  #   respond_to do |format|
  #     format.html # index.html.erb
  #     format.json { render json: @bookmarks }
  #   end
  # end

  def index
    @bookmarks = Bookmark.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @bookmarks }
    end
  end

  # GET /bookmarks/1
  # GET /bookmarks/1.json
  def show
    @bookmark = Bookmark.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @bookmark }
    end
  end

  # GET /bookmarks/new
  # GET /bookmarks/new.json
  def new
    @bookmark = Bookmark.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @bookmark }
    end
  end

  # GET /bookmarks/1/edit
  def edit
    @bookmark = Bookmark.find(params[:id])
  end

  # POST /bookmarks
  # POST /bookmarks.json
  def create
    @bookmark = Bookmark.new(params[:bookmark])

    respond_to do |format|
      if @bookmark.save
        format.html { redirect_to @bookmark, notice: 'Bookmark was successfully created.' }
        format.json { render json: @bookmark, status: :created, location: @bookmark }
      else
        format.html { render action: "new" }
        format.json { render json: @bookmark.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /bookmarks/1
  # PUT /bookmarks/1.json
  def update
    @bookmark = Bookmark.find(params[:id])

    respond_to do |format|
      if @bookmark.update_attributes(params[:bookmark])
        format.html { redirect_to @bookmark, notice: 'Bookmark was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @bookmark.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /bookmarks/1
  # DELETE /bookmarks/1.json
  def destroy
    @bookmark = Bookmark.find(params[:id])
    @bookmark.destroy

    respond_to do |format|
      format.html { redirect_to bookmarks_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController

  before_filter :authenticate_user!, only: [:new, :create, :edit, :update]

  # GET /categories
  # GET /categories.json
  def index
    @categories = Category.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @categories }
    end
  end

  # GET /categories/1
  # GET /categories/1.json
  def show
    @category = Category.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @category }
    end
  end

  # GET /categories/new
  # GET /categories/new.json
  def new
    @category = Category.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @category }
    end
  end

  # GET /categories/1/edit
  def edit
    @category = Category.find(params[:id])
  end

  # POST /categories
  # POST /categories.json
  def create
    @category = Category.new(params[:category])

    respond_to do |format|
      if @category.save
        format.html { redirect_to @category, notice: 'Category was successfully created.' }
        format.json { render json: @category, status: :created, location: @category }
      else
        format.html { render action: "new" }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /categories/1
  # PUT /categories/1.json
  def update
    @category = Category.find(params[:id])

    respond_to do |format|
      if @category.update_attributes(params[:category])
        format.html { redirect_to @category, notice: 'Category was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /categories/1
  # DELETE /categories/1.json
  def destroy
    @category = Category.find(params[:id])
    @category.destroy

    respond_to do |format|
      format.html { redirect_to categories_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/profiles_controller.rb
# class ProfilesController < ApplicationController
#   def show
#   	@user = User.find_by_profile_name(params[:id])

#   	if @user
#   		@bookmarks = @user.bookmarks.all
#   		render action: :show
#   	else
# 	  	render file: 'public/404', status: 404, formats: [:html]
#   	end
#   end
# end

class ProfilesController < ApplicationController
  def show
  	@user = User.find_by_profile_name(params[:id])

  	if @user
  		@bookmarks = @user.bookmarks.all
  		render action: :show
  	else
	  	render file: 'public/404', status: 404, formats: [:html]
  	end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
	def flash_class(type)
		case type
		when :alert
			"alert-error"
		when :notice
			"alert-success"
		else
			""
		end
	end
end

app/helpers/bookmarks_helper.rb
module BookmarksHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/views/bookmarks/_form.html.erb
<%= simple_form_for(@bookmark) do |f| %>
  <% if @bookmark.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@bookmark.errors.count, "error") %> prohibited this bookmark from being saved:</h2>

      <ul>
      <% @bookmark.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  
  <%= f.input :title %>
  <%= f.input :description %>
  <%= f.input :url %>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/bookmarks/edit.html.erb
<h1>Editing bookmark</h1>

<%= render 'form' %>

<%= link_to 'Show', @bookmark %> |
<%= link_to 'Back', bookmarks_path %>

app/views/bookmarks/index.html.erb
<div class="page-header">
  <h1>My Bookmarks</h1>
</div>

<%= link_to "Create a New Bookmark", new_bookmark_path, class: "btn btn-primary" %>

<% @bookmarks.each do |bookmark| %>
  <div class="bookmark">
    <div class="row">
      <div class="span1">
        
      </div>
      <div class="span7">
        <strong><%= bookmark.title %></strong>
        <p><%= bookmark.description %></p>
        <div class="meta">
          <span class="admin">
            <%= link_to "Edit", edit_bookmark_path(bookmark) %> |
            <%= link_to "Delete", 
              bookmark, 
              method: :delete, 
              data: {
                confirm: "Are you sure you want to delete this bookmark?"
              }
            %>
          </span>
        </div>
      </div>
    </div>
  </div>
<% end %>

app/views/bookmarks/new.html.erb
<h1>New bookmark</h1>

<%= render 'form' %>

<%= link_to 'Back', bookmarks_path %>

app/views/bookmarks/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Title:</b>
  <%= @bookmark.title %>
</p>

<p>
  <b>Description:</b>
  <%= @bookmark.description %>
</p>

<p>
  <b>Url:</b>
  <%= @bookmark.url %>
</p>


<%= link_to 'Edit', edit_bookmark_path(@bookmark) %> |
<%= link_to 'Back', bookmarks_path %>

app/views/categories/_form.html.erb
<%= form_for(@category) do |f| %>
  <% if @category.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@category.errors.count, "error") %> prohibited this category from being saved:</h2>

      <ul>
      <% @category.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_area :description %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/categories/edit.html.erb
<h1>Editing category</h1>

<%= render 'form' %>

<%= link_to 'Show', @category %> |
<%= link_to 'Back', categories_path %>

app/views/categories/index.html.erb
<h1>Listing categories</h1>

<table>
  <tr>
    <th>Title</th>
    <th>Description</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @categories.each do |category| %>
  <tr>
    <td><%= category.title %></td>
    <td><%= category.description %></td>
    <td><%= link_to 'Show', category %></td>
    <td><%= link_to 'Edit', edit_category_path(category) %></td>
    <td><%= link_to 'Destroy', category, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Category', new_category_path %>

app/views/categories/new.html.erb
<h1>New category</h1>

<%= render 'form' %>

<%= link_to 'Back', categories_path %>

app/views/categories/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Title:</b>
  <%= @category.title %>
</p>

<p>
  <b>Description:</b>
  <%= @category.description %>
</p>


<%= link_to 'Edit', edit_category_path(@category) %> |
<%= link_to 'Back', categories_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>MyBookmark</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
<div class="navbar navbar-inverse navbar-fixed-top">
            <div class="navbar-inner">
              <div class="container">
                <button type="button" class="btn btn-navbar" data-toggle="collapse" data-target="#nav-collapse-01">
                </button>
                <a href="#fakelink" class="brand">MyBookmark</a>
                <div class="nav-collapse collapse" id="nav-collapse-01">
                  <ul class="nav">
                    <li> <%= link_to "All Bookmarks", feed_path %> </li>
                  </ul>
                  <ul class="nav pull-right">
                      <% if user_signed_in? %>
                          <li><%= link_to current_user.full_name, edit_user_registration_path %></li>
                          <li><%= link_to "Log Out", logout_path %></li>
                      <% else %>
                          <li><%= link_to "Register", register_path %></li>
                          <li><%= link_to "Login", login_path %></li>
                      <% end %>
                    </ul>
                  </div>

                  <!-- <form class="navbar-search form-search pull-right" action="">
                    <div class="input-append">
                      <input type="text" class="search-query span2" placeholder="Search">
                      <button type="submit" class="btn btn-large">
                        <i class="fui-search"></i>
                      </button>
                    </div>
                  </form> -->
                </div><!--/.nav-collapse -->
              </div>
            </div>
          </div>
  <!-- <div class="navbar navbar-inverse">
    <div class="navbar-inner">
      <div class="container">
        <a href="#" class="brand">MyBookmark</a>
        <ul class="nav">
          <li> <%= link_to "All Bookmarks", feed_path %> </li>
        </ul>
        <ul class="nav pull-right">
          <% if user_signed_in? %>
            <li><%= link_to current_user.full_name, edit_user_registration_path %></li>
            <li><%= link_to "Log Out", logout_path %></li>
          <% else %>
            <li><%= link_to "Register", register_path %></li>
            <li><%= link_to "Login", login_path %></li>
          <% end %>
        </ul>
      </div>
    </div>
  </div> -->
  <div class="container">
    <% flash.each do |type, message| %>
      <div class="alert <%= flash_class type %>">
        <button class="close" data-dismiss="alert">x</button>
        <%= message %>
      </div>
    <% end %>
    <%= yield %>
  </div>
</body>
</html>

app/views/profiles/show.html.erb
<div class="page-header">
	<h1><%= @user.full_name %></h1>
</div>

<% if @bookmarks %>
	<% @bookmarks.each do |status| %>
		<div class="well">
			<%= bookmark.content %>
		</div>
		<hr />
		<%= link_to time_ago_in_words(bookmark.created_at), bookmark_path(status) %> ago
	<% end %>
<% end %>